backend:
  name: github
  branch: main
  repo: Max-Rosenblatt/riskbase-docs

media_folder: "static/img" # Media files will be stored in the repo under static/img
public_folder: "/img/" # The src attribute for uploaded media will begin with /img/

collections:
  - name: "get_started"
    label: "Get Started"
    files:
      - label: "Get Started"
        name: "get_started"
        file: "docs/GetStarted.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "admin"
    label: "Admin"
    folder: "docs/Admin"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "app"
    label: "App"
    folder: "docs/app"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "how-to"
    label: "How-To"
    folder: "docs/How-To"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "riskbase"
    label: "Riskbase"
    folder: "docs/Riskbase"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
